mod.id = "metrakron"
mod.name = "ERYDON Metrakron"
mod.group = "com.oliver.metrakron"
mod.version = "0.2.0"

deps.fabric_loader = "0.16.10"
loomx.loom_version = "1.17.20"

["1.18.2"]
mod.mc_compat = "1.18.2"
deps.yarn_mappings = "1.18.2+build.4"
deps.fabric_api = "0.77.0+1.18.2"

["1.19.2"]
mod.mc_compat = "1.19.2"
deps.yarn_mappings = "1.19.2+build.28"
deps.fabric_api = "0.77.0+1.19.2"

["1.19.4"]
mod.mc_compat = "1.19.4"
deps.yarn_mappings = "1.19.4+build.2"
deps.fabric_api = "0.87.2+1.19.4"

["1.20.1"]
mod.mc_compat = "1.20.1"
deps.yarn_mappings = "1.20.1+build.10"
deps.fabric_api = "0.92.11+1.20.1"

["1.20.4"]
mod.mc_compat = "1.20.4"
deps.yarn_mappings = "1.20.4+build.3"
deps.fabric_api = "0.97.3+1.20.4"

["1.20.6"]
mod.mc_compat = "1.20.6"
deps.yarn_mappings = "1.20.6+build.3"
deps.fabric_api = "0.100.8+1.20.6"

["1.21.1"]
mod.mc_compat = "1.21.1"
deps.yarn_mappings = "1.21.1+build.3"
deps.fabric_api = "0.116.15+1.21.1"

["1.21.4"]
mod.mc_compat = "1.21.4"
deps.yarn_mappings = "1.21.4+build.8"
deps.fabric_api = "0.119.4+1.21.4"

["1.21.8"]
mod.mc_compat = "1.21.8"
deps.fabric_loader = "0.16.13"
deps.yarn_mappings = "1.21.8+build.1"
deps.fabric_api = "0.136.1+1.21.8"

["1.21.11"]
mod.mc_compat = "1.21.11"
deps.fabric_loader = "0.17.3"
deps.yarn_mappings = "1.21.11+build.6"
deps.fabric_api = "0.141.6+1.21.11"

["26.1.2"]
mod.mc_compat = "26.1.2"
deps.fabric_loader = "0.18.4"
deps.fabric_api = "0.155.2+26.1.2"

["26.2"]
mod.mc_compat = "26.2"
deps.fabric_loader = "0.19.3"
deps.fabric_api = "0.158.0+26.2"
